[http_server]
port = "3030"
url = "http://localhost:3030"
token_file = "/usr/local/token.txt"
grpc_connection_pool = 20

[log]
level = "info"
appender = "console"
log_dir = "/usr/local/mcs/log"
log_prefix = "mcs.log"

[udp_server]
socket_file = "/usr/local/mcs/mcs-ds.sock"

[fs_esl_client]
host = "127.0.0.1:8021"
auth = "ClueCon"